[package]
name = "keytao-dict-checker"
version = "0.2.0"
edition = "2024"
license = "MIT"
publish = false
readme = "README.md"
repository = "https://github.com/xkinput/keytao-dict-checker"
rust-version = "1.98.0"
description = "「RIME 键道」词库检查器"

[dependencies]
ahash = { version = "0.8.12", default-features = false, features = ["std", "no-rng"] }
rayon = "1.12.0"
saphyr = { version = "0.0.12", default-features = false }

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
strip = "symbols"
