name: Release

on:
  push:
    tags:
      - 'v*'

env:
  BINARY_NAME: keytao-dict-checker
  CARGO_TERM_COLOR: always

jobs:
  release:
    permissions:
      contents: write

    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            suffix: .exe
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            suffix: ''
          - os: macos-latest
            target: aarch64-apple-darwin
            suffix: ''

    runs-on: ${{ matrix.os }}

    steps:
      - name: 禁用换行符转换
        run: git config --global core.autocrlf false
      - name: 检出代码
        uses: actions/checkout@v6
      - name: 安装工具链
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.96
          targets: ${{ matrix.target }}
      - name: 构建
        run: cargo build -r --target ${{ matrix.target }}
      - name: 打包
        shell: bash
        run: |
          PKG=${{ env.BINARY_NAME }}-${{ github.ref_name }}-${{ matrix.target }}
          mkdir $PKG
          cp target/${{ matrix.target }}/release/${{ env.BINARY_NAME }}${{ matrix.suffix }} $PKG/
          cp config.toml LICENSE README.md $PKG/
          7z a -t7z -mx=9 -m0=lzma2 $PKG.7z $PKG
      - name: 发布
        uses: softprops/action-gh-release@v3
        with:
          files: "*.7z"
